---
title: "Affiliate data & Country-level data: 子会社データと国データの接続"
author: "Ayumu Tanaka"
date: "2024-05-18"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: yes
#bibliography: ref.bib
link-citations: yes
---

```{r setup-chunk, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, # Display codes
                      cache = FALSE, # do not Cache the results
                      message=FALSE, # Suppress messages
                      warning=FALSE) # Suppress warnings

```

# Preparation


```{r preparation}
# Remove all data
rm(list = ls())

# Load the necessary libraries
library("rio")           # For importing data 
library("tidyverse")     # For data manipulation
library("countrycode")   # For creating the country ISO codes
library("Hmisc")         # For labeling the variables
```




# Load the data データ読み込み


以下のデータを読み込む。

- "FA3": 日本の海外子会社の基本データ

```{r load-data}

FA4  <- rio::import("../Data_output/FA4.rds")

```


# The number of affiliates in EU

EUにおける海外子会社数を計算する。

```{r number-affiliates-EU}

# Create a dummy variable for iso == GBR
  FA4 <- FA4 %>% 
    mutate(GBR = ifelse(iso == "GBR", 1, 0))

# Creating the number of affiliate in GBR
  FA4 <- FA4 %>%
    group_by(JPCode, year) %>%
    mutate(N_Aff_GBR = sum(GBR))

# Creating the number of affiliates in EU
  FA4 <- FA4 %>%
    group_by(JPCode, year) %>%
    mutate(N_Aff_EU = sum(euall))

# Substracting N_Aff_GBR from N_Aff_EU
  FA4 <- FA4 %>%
    mutate(N_Aff_EU = N_Aff_EU - N_Aff_GBR)
```

  

# Barlot by the existence of affiliates in EU
```{r barplot-existence-affiliates-EU}
  FA4$N_Aff_EU_dummy <- ifelse(FA4$N_Aff_EU > 0, 1, 0)
  
  barplot(table(FA4$N_Aff_EU_dummy), 
          main = "The existence of affiliates in EU except the UK")
  FA4$N_Aff_EU_dummy <- NULL
```

# Histogram of the number of affiliates in EU  if N_Aff_EU > 0
```{r histogram-affiliates-EU}
  barplot(table(FA4$N_Aff_EU[FA4$N_Aff_EU > 0]),
          main = "The number of affiliates in EU except the UK")
```

# Summary statistics of the number of affiliates in EU
```{r summary-affiliates-EU}

# Mean of the number of affiliates in EU
  mean(FA4$N_Aff_EU, na.rm = TRUE)

# # Mean of the number of affiliates in EU if N_Aff_EU > 0
  mean(FA4$N_Aff_EU[FA4$N_Aff_EU > 0], na.rm = TRUE)

```

# Save the data
```{r save-data}
# Save the data
rio::export(FA4, "../Data_output/FA5.rds")
```





